### ISSUE TITLE
toontown-online branch: fire hydrant has no color

### ISSUE THREAD

**Issue by v1tal** [toonjoey/toontown-project-bikehorn#17]
This could be user error since I just merged the textures over a Toontown School House install but any help with this would be appreciated. If this is my fault and not an issue with the pack then I apologize 

![image](https://github.com/toonjoey/toontown-project-bikehorn/assets/13513301/1be9c243-3533-4f04-9e57-91462769a7d9)

**Comment by toonjoey** [comment]
_That_ is odd. I'll have to take a look on my own personal Toontown Online source, but that's using an entirely different texture, and I think I know which one...

**Comment by toonjoey** [comment]
![image](https://github.com/toonjoey/toontown-project-bikehorn/assets/19507339/490a389a-0a91-43fd-b75b-1efa40a9418b)

(It is worth noting in all fairness, I haven't messed with Schoolhouse. But the textures should all be the same, no? Weird.)

**Comment by toonjoey** [comment]
![image](https://github.com/toonjoey/toontown-project-bikehorn/assets/19507339/fee10d05-feaf-495d-80bc-d4a78f552fc4)

This is the palette as it appears in Schoolhouse, which is (for some reason) completely different from Toontown Online. You could rearrange the palette yourself in an image editing program of your choice (might I recommend paint.net?), but that's about all you can do since I don't plan on supporting projects other than Rewritten and Online at the moment.

**Comment by v1tal** [comment]
Thank you for the guidance! Uploading this here in case anyone else wants to apply this pack to the source as well

![phase_5_palette_3cmla_1](https://github.com/toonjoey/toontown-project-bikehorn/assets/13513301/3d614233-7bc2-4e92-8db9-023421df25c2)
